# Site settings
title: Between Two Ears
email: me@benny.id
description: > # this means to ignore newlines until "baseurl:"
  Between Two Ears is a blog by Benny Chandra that contains his thought
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benny.id" # the base hostname & protocol for your site
twitter_username: scalarae

# Build settings
markdown: kramdown

# Pagination
paginate: 5
paginate_path: "/blog/page:num"
