application: benny-id-landing-page
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*)/$
  static_files: _site/\1/index.html
  upload: _site/(.*)/index.html

- url: /(.+)
  static_files: _site/\1
  upload: _site/(.*)

- url: /
  static_files: _site/index.html
  upload: _site/index.html
